@echo off
echo Starting the application server...
start "" python app.py
echo Waiting for server to start...
timeout /t 3 /nobreak > nul
echo Opening the application in your browser...
start http://127.0.0.1:5000/
exit